### ISSUE TITLE
How to align more sequence?

### ISSUE THREAD

**Issue by haojingshao** [TF-Chan-Lab/OMBlast#1]
Dear OMBlast developer,
Recently, I tried to compare the result of OMBlast with RefAlign. I found that OMBlast preferred to align less or shorter sequence than RefAlign. I tried to modify the parameter of maxfpr and maxfnr. I didn't get a different result.
Is there a way to align more sequence? (FP could be increased)
Thanks,
Haojing

**Comment by aldenleung** [comment]
Dear Haojing,

Thanks for your interest in using OMBlast. You could align more molecules by tuning the following parameters:

Error tolerance: --meas, --ear, --falselimit; By increasing the error tolerance, you will get more molecules aligned and longer alignment. This will increase the false positive rate and running time. (You need to lower the uniqueness as mentioned below) 
Score filter: --minscore and --minclusterscore; Decreasing these two parameters to output more alignments (with lower quality)
Uniqueness filter: --minconf; Lower the parameter to output more alignments

Best,
Alden

**Comment by haojingshao** [comment]
It is working now. Thank you very much.

**Comment by aldenleung** [comment]
You're welcome. Other than the parameters mentioned before, if you want to output more than one alignments, you can increase the parameter --maxclusteritem, or set it to -1 to output all possible alignments. In this case, you need to set the uniqueness filter to 0 (because you no longer need the uniqueness test on the results).
